"""Shared constants for EUDAMED Excel/XML scripts."""

from __future__ import annotations

XML_NS = {
    "message": "https://ec.europa.eu/tools/eudamed/dtx/servicemodel/Message/v1",
    "service": "https://ec.europa.eu/tools/eudamed/dtx/servicemodel/Service/v1",
    "device": "https://ec.europa.eu/tools/eudamed/dtx/datamodel/Entity/Device/v1",
    "e": "https://ec.europa.eu/tools/eudamed/dtx/datamodel/Entity/v1",
    "budi": "https://ec.europa.eu/tools/eudamed/dtx/datamodel/Entity/Device/BasicUDI/v1",
    "udidi": "https://ec.europa.eu/tools/eudamed/dtx/datamodel/Entity/UDIDI/v1",
    "commondevice": "https://ec.europa.eu/tools/eudamed/dtx/datamodel/Entity/Device/CommonDevice/v1",
    "lngs": "https://ec.europa.eu/tools/eudamed/dtx/datamodel/Entity/Common/LanguageSpecific/v1",
    "mktinfo": "https://ec.europa.eu/tools/eudamed/dtx/datamodel/Entity/MktInfo/MarketInfo/v1",
    "lnks": "https://ec.europa.eu/tools/eudamed/dtx/datamodel/Entity/Links/v1",
    "xsi": "http://www.w3.org/2001/XMLSchema-instance",
}

XML_TAGS = {
    "message.pull_response": ("message", "PullResponse"),
    "message.conversation_id": ("message", "conversationID"),
    "message.correlation_id": ("message", "correlationID"),
    "message.creation_datetime": ("message", "creationDateTime"),
    "message.message_id": ("message", "messageID"),
    "message.recipient": ("message", "recipient"),
    "message.node": ("message", "node"),
    "message.service": ("message", "service"),
    "message.payload": ("message", "payload"),
    "message.sender": ("message", "sender"),
    "message.number_of_pages": ("message", "numberOfPages"),
    "message.page_number": ("message", "pageNumber"),
    "message.page_size": ("message", "pageSize"),
    "message.response_code": ("message", "responseCode"),
    "service.node_actor_code": ("service", "nodeActorCode"),
    "service.service_id": ("service", "serviceID"),
    "service.service_operation": ("service", "serviceOperation"),
    "device.device": ("device", "Device"),
    "device.mdr_basic_udi": ("device", "MDRBasicUDI"),
    "device.mdr_udidi_data": ("device", "MDRUDIDIData"),
    "entity.state": ("e", "state"),
    "entity.version": ("e", "version"),
    "entity.version_date": ("e", "versionDate"),
    "budi.risk_class": ("budi", "riskClass"),
    "budi.model_name": ("budi", "modelName"),
    "budi.model": ("budi", "model"),
    "budi.identifier": ("budi", "identifier"),
    "budi.device_certificate_links": ("budi", "deviceCertificateLinks"),
    "budi.mf_actor_code": ("budi", "MFActorCode"),
    "budi.iib_implantable_exceptions": ("budi", "IIb_implantable_exceptions"),
    "budi.type": ("budi", "type"),
    "budi.animal_tissues_cells": ("budi", "animalTissuesCells"),
    "budi.human_tissues_cells": ("budi", "humanTissuesCells"),
    "budi.human_product_check": ("budi", "humanProductCheck"),
    "budi.medicinal_product_check": ("budi", "medicinalProductCheck"),
    "commondevice.model": ("commondevice", "model"),
    "commondevice.name": ("commondevice", "name"),
    "commondevice.di_code": ("commondevice", "DICode"),
    "commondevice.issuing_entity_code": ("commondevice", "issuingEntityCode"),
    "commondevice.active": ("commondevice", "active"),
    "commondevice.administering_medicine": ("commondevice", "administeringMedicine"),
    "commondevice.implantable": ("commondevice", "implantable"),
    "commondevice.measuring_function": ("commondevice", "measuringFunction"),
    "commondevice.reusable": ("commondevice", "reusable"),
    "commondevice.code": ("commondevice", "code"),
    "udidi.identifier": ("udidi", "identifier"),
    "udidi.status": ("udidi", "status"),
    "udidi.basic_udi_identifier": ("udidi", "basicUDIIdentifier"),
    "udidi.mdn_codes": ("udidi", "MDNCodes"),
    "udidi.production_identifier": ("udidi", "productionIdentifier"),
    "udidi.reference_number": ("udidi", "referenceNumber"),
    "udidi.secondary_identifier": ("udidi", "secondaryIdentifier"),
    "udidi.sterile": ("udidi", "sterile"),
    "udidi.sterilization": ("udidi", "sterilization"),
    "udidi.latex": ("udidi", "latex"),
    "udidi.reprocessed": ("udidi", "reprocessed"),
    "udidi.trade_names": ("udidi", "tradeNames"),
    "udidi.additional_description": ("udidi", "additionalDescription"),
    "udidi.website": ("udidi", "website"),
    "udidi.number_of_reuses": ("udidi", "numberOfReuses"),
    "udidi.base_quantity": ("udidi", "baseQuantity"),
    "lngs.name": ("lngs", "name"),
    "lngs.language": ("lngs", "language"),
    "lngs.text_value": ("lngs", "textValue"),
    "lnks.device_certificate_link": ("lnks", "deviceCertificateLink"),
    "lnks.certificate_number": ("lnks", "certificateNumber"),
    "lnks.expiry_date": ("lnks", "expiryDate"),
    "lnks.nb_actor_code": ("lnks", "NBActorCode"),
    "lnks.certificate_revision_number": ("lnks", "certificateRevisionNumber"),
    "lnks.certificate_type": ("lnks", "certificateType"),
}

SHEET_PREFIXES = {
    "basic": "Basic UDI-DI information",
    "cert": "Certificate information",
    "ident": "UDI-DI identification",
    "chars": "UDI-DI characteristics",
    "device": "Device information",
}

HEADERS = {
    "risk_class": "Risk class*",
    "device_model": "Device Model",
    "device_name": "Device Name*",
    "issuing_entity": "UDI-DI identification Issuing Entity (GS1/HIBCC/ICCBBA/IFA)",
    "udi_di_code": "UDI-DI code",
    "udi_di_status": "UDI-DI status ( On the EU market / No longer placed on the EU market / Not intended for the EU market )",
    "manufacturer_srn": "Manufacturer Actor Code (SRN)",
    "mf_actor_code": "MFActorCode",
    "emdn_code": "Enter a nomenclature code (EMDN code)",
    "reference_number": "Reference/Catalogue number",
    "single_use": "Labelled as single use",
    "max_reuses": "Maximum number of reuses",
    "trade_name": "Trade name",
    "language": "Select the language",
    "additional_description": "Additional product description",
    "website": "URL for additional information (as electronic instructions for use)",
    "quantity": "Quantity of device",
    "secondary_applicable": "UDI-DI from another entity (secondary) applicable",
    "secondary_issuer": "Secondary Issuing Entity (GS1/HIBCC/ICCBBA/IFA)",
    "secondary_code": "Secondary UDI-DI code",
    "sterile": "Device labelled as sterile",
    "sterilization": "Need for sterilisation before use",
    "latex": "Containing latex",
    "reprocessed": "Reprocessed single use device",
    "model_applicable": "Device model applicable",
    "implantable": "Implantable*",
    "measuring_function": "Measuring function*",
    "reusable": "Reusable surgical instrument*",
    "active": "Active device*",
    "administering_medicine": "Device intended to administer and/or remove medicinal product*",
    "animal_tissues": "Tissues and cells Presence of animal tissues or cells, or their derivatives:",
    "human_tissues": "Tissues and cells Presence of human tissues or cells, or their derivatives:",
    "human_blood_product": "Presence of a substance which, if used separately, may be considered to be a medicinal product derived from human blood or human plasma(Y/N)",
    "medicinal_product": "Information on substances Presence of a substance which, if used separately, may be considered to be a medicinal product (Y/N)",
    "cert_applicable": "Certificate applicable",
    "nb_actor_code": "Notified Body Actor Code (NBActorCode)",
    "cert_type": "Certificate type",
    "cert_number": "Certificate number",
    "cert_revision": "Certificate revision number",
    "cert_expiry": "Certificate expiry date (YYYY-MM-DD)",
    "member_state_placement": "Member State where device is placed on market (e.g., IT, DE, FR)",
    "member_states_available": "Member States where device is made available (comma-separated, e.g., IT,DE,FR)",
    "is_system_spp": "Is it a System or Procedure pack which is a Device in itself (Y/N)",
    "is_kit": "Is it a Kit (Y/N)",
    "special_device_type": "Special Device Type (if applicable)",
    "iib_exception_flag": "IIb implantable exceptions: Is device a suture/staple/dental/screw/etc (Y/N)",
    "iib_exception_type": "IIb implantable exceptions: Specify device type (suture, staple, dental filling, screw, etc.)",
    "pi_lot": "Type of UDI-PI Lot or Batch number",
    "pi_serial": "Type of UDI-PI Serial number",
    "pi_mfg_date": "Type of UDI-PI Manufacturing date",
    "pi_exp_date": "Type of UDI-PI Expiration date",
    "clinical_size_status": "Clinical size application status",
}

TEMPLATE_SHEETS = {
    SHEET_PREFIXES["basic"]: [
        HEADERS["risk_class"],
        HEADERS["model_applicable"],
        HEADERS["device_model"],
        HEADERS["device_name"],
        HEADERS["implantable"],
        HEADERS["measuring_function"],
        HEADERS["reusable"],
        HEADERS["active"],
        HEADERS["administering_medicine"],
        HEADERS["is_system_spp"],
        HEADERS["is_kit"],
        HEADERS["special_device_type"],
        HEADERS["iib_exception_flag"],
        HEADERS["iib_exception_type"],
    ],
    SHEET_PREFIXES["cert"]: [
        HEADERS["cert_applicable"],
        HEADERS["nb_actor_code"],
        HEADERS["cert_type"],
        HEADERS["cert_number"],
        HEADERS["cert_revision"],
        HEADERS["cert_expiry"],
    ],
    SHEET_PREFIXES["ident"]: [
        HEADERS["issuing_entity"],
        HEADERS["udi_di_code"],
        HEADERS["reference_number"],
        HEADERS["website"],
        HEADERS["udi_di_status"],
        HEADERS["member_state_placement"],
        HEADERS["member_states_available"],
        HEADERS["quantity"],
        HEADERS["secondary_applicable"],
        HEADERS["secondary_issuer"],
        HEADERS["secondary_code"],
        HEADERS["emdn_code"],
        HEADERS["trade_name"],
        HEADERS["language"],
        HEADERS["additional_description"],
        HEADERS["language"],
        HEADERS["pi_lot"],
        HEADERS["pi_serial"],
        HEADERS["pi_mfg_date"],
        HEADERS["pi_exp_date"],
    ],
    SHEET_PREFIXES["chars"]: [
        HEADERS["sterilization"],
        HEADERS["sterile"],
        HEADERS["latex"],
        HEADERS["single_use"],
        HEADERS["max_reuses"],
        HEADERS["clinical_size_status"],
    ],
    SHEET_PREFIXES["device"]: [
        HEADERS["human_tissues"],
        HEADERS["animal_tissues"],
        HEADERS["medicinal_product"],
        HEADERS["human_blood_product"],
        HEADERS["reprocessed"],
    ],
}

TEMPLATE_EXAMPLES = {
    SHEET_PREFIXES["basic"]: {
        HEADERS["risk_class"]: "Class IIa",
        HEADERS["model_applicable"]: "Yes",
        HEADERS["device_model"]: "MODEL-100",
        HEADERS["device_name"]: "Example Device",
        HEADERS["implantable"]: "No",
        HEADERS["measuring_function"]: "Yes",
        HEADERS["reusable"]: "No",
        HEADERS["active"]: "No",
        HEADERS["administering_medicine"]: "No",
        HEADERS["is_system_spp"]: "No",
        HEADERS["is_kit"]: "No",
        HEADERS["special_device_type"]: "",
        HEADERS["iib_exception_flag"]: "No",
        HEADERS["iib_exception_type"]: "",
    },
    SHEET_PREFIXES["ident"]: {
        HEADERS["issuing_entity"]: "GS1",
        HEADERS["udi_di_code"]: "01234567890123",
        HEADERS["udi_di_status"]: "On the EU market",
        HEADERS["member_state_placement"]: "IT",
        HEADERS["member_states_available"]: "IT,DE,FR",
        HEADERS["emdn_code"]: "A0000",
        HEADERS["trade_name"]: "Example Trade Name",
        HEADERS["language"]: "EN",
        HEADERS["pi_lot"]: "Yes",
    },
    SHEET_PREFIXES["chars"]: {
        HEADERS["sterilization"]: "No",
        HEADERS["sterile"]: "No",
        HEADERS["latex"]: "No",
        HEADERS["single_use"]: "Yes",
        HEADERS["max_reuses"]: "0",
        HEADERS["clinical_size_status"]: "No",
    },
    SHEET_PREFIXES["cert"]: {
        HEADERS["cert_applicable"]: "Yes",
        HEADERS["nb_actor_code"]: "NB 0123",
        HEADERS["cert_type"]: "MDR_TYPE_EXAMINATION",
        HEADERS["cert_number"]: "CERT-2026-0001",
        HEADERS["cert_revision"]: "1",
        HEADERS["cert_expiry"]: "2030-12-31",
    },
}

GUIDE_HEADERS = ["Field", "Required For", "Notes"]

TEMPLATE_GUIDANCE_ROWS = [
    (
        HEADERS["risk_class"],
        "All",
        "Use values such as Class I, Class IIa, Class IIb, Class III. (BR-UDID-676: Class I forces Implantable=No)",
    ),
    (
        f"{HEADERS['device_name']} or {HEADERS['device_model']}",
        "All",
        "At least one should be provided. (BR-UDID-066)",
    ),
    (
        HEADERS["implantable"],
        "All",
        "If Yes and Risk Class IIb, device type must be specified (BR-UDID-635). If Yes, Reusable surgical instrument auto-forced to No (BR-UDID-677).",
    ),
    (
        "IIb implantable exceptions",
        "Class IIb with Implantable=Yes",
        "Required for Class IIb implantable devices (BR-UDID-635). Specify: suture, staple, dental filling, dental brace, tooth crown, screw, wedge, plate, wire, pin, clip, or connector.",
    ),
    (
        HEADERS["single_use"],
        "All",
        "If No, then Max reuses must be provided. (BR-UDID-024)",
    ),
    (
        HEADERS["max_reuses"],
        "If single use = No",
        "Only applicable if NOT single-use. (BR-UDID-024)",
    ),
    (
        "Member State fields",
        "Class IIa, IIb, III (when on market)",
        "Required for placed on market / made available. (BR-UDID-043, BR-UDID-673, BR-UDID-674)",
    ),
    (
        "Is it a System/SPP/Kit",
        "Conditional",
        "If System/SPP=Yes or Kit=Yes, then Special Device Type cannot be set. (BR-UDID-705)",
    ),
    (
        HEADERS["additional_description"],
        "If System/SPP/Kit",
        "Mandatory for System, Procedure pack, or Kit devices. (BR-UDID-131)",
    ),
    (
        f"{HEADERS['udi_di_code']} + {HEADERS['issuing_entity']}",
        "All",
        "Must uniquely identify the UDI-DI. (BR-UDID-003)",
    ),
    (
        "UDI-DI status",
        "All",
        "Use one of: On the EU market, No longer placed on the EU market, Not intended for the EU market. (BR-UDID-458, BR-UDID-073)",
    ),
    (
        "Trade name + language",
        "All",
        "Language should be 2/3-letter code (for example EN, FR, ANY). (BR-UDID-070)",
    ),
    (
        "Certificate information",
        "Class III (required), Class I with measuring (required), others (optional)",
        "If Certificate applicable is Yes, provide NBActorCode and Certificate type at minimum. (BR-UDID-113)",
    ),
]
